# Generated by Django 5.1.6 on 2025-02-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(blank=True, max_length=150, null=True,
                                          verbose_name='Что именно необходимо выполнить')),
                ('when', models.TimeField(blank=True, help_text='формат H:M', null=True,
                                          verbose_name='Время, когда необходимо выполнять привычку')),
                ('where', models.CharField(blank=True, max_length=150, null=True,
                                           verbose_name='Место, где необходимо выполнять привычку')),
                ('enjoyable', models.BooleanField(blank=True, null=True, verbose_name='Признак приятной привычки ')),
                ('reward', models.TextField(blank=True, null=True, verbose_name='Вознаграждение')),
                ('period', models.PositiveSmallIntegerField(blank=True,
                                                            help_text='по умолчанию ежедневно, но не менее 1 рза в 7 дней',
                                                            null=True,
                                                            verbose_name='периодичность выполнения привычки в днях')),
                ('time_to_complete',
                 models.PositiveSmallIntegerField(blank=True, help_text='не больше 120 секунд', null=True,
                                                  verbose_name='время на выполнение привычки в секундах')),
                ('is_private', models.BooleanField(blank=True, null=True, verbose_name='Признак приватности привычки')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
