# Generated by Django 5.1.6 on 2025-02-18 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('routine', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='reward_routine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='routine.routine', verbose_name='Приятная привычка'),
        ),
    ]
