# Generated by Django 5.1.6 on 2025-02-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('routine', '0004_alter_routine_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='period',
            field=models.PositiveSmallIntegerField(blank=True, default=1,
                                                   help_text='по умолчанию ежедневно, но не менее 1 раза в 7 дней',
                                                   null=True, verbose_name='периодичность выполнения привычки в днях'),
        ),
    ]
