# Generated by Django 5.1.6 on 2025-02-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('routine', '0005_alter_routine_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='is_private',
        ),
        migrations.AddField(
            model_name='routine',
            name='is_public',
            field=models.BooleanField(blank=True, null=True, verbose_name='Признак публичности привычки'),
        ),
    ]
