# Generated by Django 5.1.6 on 2025-02-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('routine', '0006_remove_routine_is_private_routine_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='last_reminder',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего напоминания'),
        ),
        migrations.AddField(
            model_name='routine',
            name='reminder',
            field=models.BooleanField(blank=True, null=True, verbose_name='Включить напоминания'),
        ),
    ]
